<?php

define('RINGO_BASE_CACHE_RINGO_ENDPOINTS', REQUEST_TIME + 3600);

require_once dirname(__FILE__) . '/includes/assign_bundle.inc';
require_once dirname(__FILE__) . '/includes/ringo_api_calls.inc';
require_once dirname(__FILE__) . '/soap/DealerWs/DealerWs.php';
require_once dirname(__FILE__) . '/soap/ManagementWs/ManagementWs.php';
require_once dirname(__FILE__) . '/uc_eshop_checkout_pane.inc';

function ringo_eshop_menu() {
  $items = array();
  $items['my-ringo/manage-bundles'] = array(
    'title' => 'My Offers',
    'page callback' => '_ringo_eshop_build_international_offers',
    //'page callback' => 'drupal_get_form',
    //'page arguments' => array('assign_eshop_international_bundle_form'),
    'access callback' => 'user_is_logged_in',
    'file' => 'assign_bundle.inc',
    'file path' => drupal_get_path('module', 'ringo_eshop') . '/includes',
  );
  return $items;
}
/**
 * Implementation of hook_uc_checkout_pane()
 */

function ringo_eshop_uc_checkout_pane() {
  $panes[] = array(
    'id' => 'id_document',
    'title' => t('ID Document'),
     'desc' => t('Provide customers to add ID document information'),
     'callback' => 'ringo_eshop_id_document_pane_checkout',
     'process' => TRUE,
     'weight' => 3,
   );
  $panes[] = array(
    'id' => 'ringo_contact_info',
    'title' => t('Contact info'),
     'desc' => t('Provide customers to add contact information'),
     'callback' => 'ringo_eshop_contact_info_pane_checkout',
     'process' => TRUE,
     'weight' => 2,
   );

   return $panes;
}


function ringo_eshop_uc_add_to_cart($nid, $qty, $data) {
  $sim_id = variable_get('ringo_eshop_sim_id', 30);
  if ($nid == $sim_id) {
    global $user;
    $oid = $data['attributes'][2];
    db_insert('ringo_eshop_numbers')
      ->fields(array(
        'oid' => $oid,
        'uid' => $user->uid,
        'status' => 1,
      ))
      ->execute();
  }
}

function ringo_eshop_form_alter(&$form, &$form_state, $form_id) {
  $sim_id = variable_get('ringo_eshop_sim_id', 30);
  if ($form_id == 'uc_product_add_to_cart_form_'.$sim_id) {
    //drupal_add_js(drupal_get_path('module', 'ringo_eshop') . '/js/national_bundles.js', array('group' => JS_THEME));
    $query = db_select('ringo_eshop_numbers', 'rn');
    $query->addField('rn', 'oid');
    $locked_options = $query->execute()->fetchAllKeyed(0, 0);
    $form['attributes'][2]['#options'] = array_diff_key($form['attributes'][2]['#options'], $locked_options);
    // add national offers
    $summary_text = t('You designed an offer of !blue_start !voice minutes, !sms SMS &amp; !data GB !blue_end for
  an estimated monthly bill of "!price € / month"',
      array(
        '!blue_start' => '<span class="blue-color">',
        '!voice' => '<span class="voice">0</span>',
        '!sms' => '<span class="sms">0</span>',
        '!data' => '<span class="data">0</span>',
        '!price' => '<span class="purple-color"><span class="total">0</span>',
        '!blue_end' => '</span>',
      ));
    //$form['attributes'][4]['#description'] = format_string('<p class="nat-bundle-desc">!summary</p>', array('!summary' => $summary_text));
    $form['attributes'][4]['#prefix'] = '<div id="national-bundle-details">';
    $form['attributes'][4]['#suffix'] = format_string('<p class="nat-bundle-desc">!summary</p>', array('!summary' => $summary_text)) .'</div>';
    $form['attributes'][5]['#prefix'] = '<div id="international-bundle-details">';
    $form['attributes'][5]['#suffix'] = format_string('<p class="internat-bundle-desc"></p>') .'</div>';
    $form['tabs'] = array(
      '#markup' => '<div id="tabs"><ul><li><a href="#tabs-1">Tab 1</a></li><li><a href="#tabs-2">Tab 2</a></li></ul>',
    );
    $form += _ringo_eshop_build_national_offers();
    $form += _ringo_eshop_build_international_offers();
  }
}

/**
 *Implements of hook_uc_cart_alter().
 */
function ringo_eshop_uc_cart_alter(&$items) {
  $sim_id = variable_get('ringo_eshop_sim_id', 30);
  foreach ($items as $id => $item) {
    if ($item->nid == $sim_id) {
      $pattern = '/"([0-9].*?)€/';
      if (!empty($item->data['attributes'][4])) {
        preg_match($pattern, $item->data['attributes'][4], $matches);
        if (isset($matches[1])) {
          $items[$id]->price += intval($matches[1]);
        }
      }
      if (!empty($item->data['attributes'][5])) {
        preg_match_all($pattern, $item->data['attributes'][5], $matches);
        foreach ($matches[1] as $price) {
          $items[$id]->price += intval($price);
        }
      }
    }
  }
}

function ringo_eshop_uc_cart_item_delete($entity) {
  $sim_id = variable_get('ringo_eshop_sim_id', 30);
  if ($entity->nid == $sim_id) {
    $oid =  $entity->data['attributes'][2];
    db_delete('ringo_eshop_numbers')
      ->condition('oid', $oid)
      ->execute();
  }
}

function _ringo_eshop_build_national_offers() {
  $national_offers = array();
  $cid = 'national_offers';
  if ($cache = cache_get($cid)) {
    $national_offers = $cache->data;
  }
  $national_offers = get_national_offers();
  return assign_national_bundle_form($national_offers);
}

function _ringo_eshop_build_international_offers() {
  $international_offers = array();
  $cid = 'international_offers';
  if ($cache = cache_get($cid)) {
    $international_offers = $cache->data;
  }
  //$international_offers = get_international_offers();
  //return _ringo_eshop_assign_international_bundle_form($international_offers);
  return drupal_get_form('assign_eshop_international_bundle_form');
}


function _ringo_eshop_assign_international_bundle_form($international_promotions) {
  $form = array();
  $user_regions = array();

  // Add bundle field set.
  $form['select-int-bundle'] = array(
    '#type' => 'fieldset',
    '#title' => t('International bundles'),
  );


  $regions = array();
  $table_region = NULL;
  $taken_bundles = array();
  foreach ($international_promotions as $region_promotions) {
    $region_id = $region_promotions['regionId'];

    // If all bundles are taken, skip this region.
    if (isset($user_regions[$region_id])) {
      if (count($user_regions[$region_id]) == count($region_promotions['bundles'])) {
        continue;
      }
    }

    $regions[$region_promotions['regionId']] = t($region_promotions['regionName']);

    // Show selected country if any.
    if (isset($form_state['values']['int-region']) && $form_state['values']['int-region'] == $region_promotions['regionId']) {
      $table_region = $region_promotions;
      $taken_bundles = isset($user_regions[$region_id]) ? $user_regions[$region_id] : array();
    }

    // Show first country by default.
    if (is_null($table_region)) {
      $table_region = $region_promotions;
      $taken_bundles = isset($user_regions[$region_id]) ? $user_regions[$region_id] : array();
    }
  }

  $form['select-int-bundle']['int-region'] = array(
    '#type' => 'select',
    '#options' => $regions,
    '#ajax' => array(
      'event' => 'change',
      'wrapper' => 'select-int-wrapper',
      'callback' => 'int_bundle_selection_change_callback',
      'method' => 'replace',
    ),
  );

  if (!is_null($table_region)) {
    $form['select-int-bundle']['int-bundle'] = get_international_table(
      $table_region,
      TRUE,
      $taken_bundles
    );

    $form['select-int-bundle']['int-bundle']['#prefix'] = '<div id="select-int-wrapper" >';
    $form['select-int-bundle']['int-bundle']['#suffix'] = '</div>';
  }
  else {
    $form['select-int-bundle']['int-bundle'] = array(
      '#markup' => '<div id="select-int-wrapper" ></div>',
    );
  }
  $form['select-int-bundle']['skip'] = array(
    '#markup' => '<div class="skip-bundle" onclick="toggle_bundle(\'national\');">'. t('Go to national bundle') .'</div>',
  );
  return $form;
}


/**
 * Implements of hook_init().
 */
function ringo_eshop_init() {
  // Redirect to SIM cart product page
  if ($_GET['q'] == 'taxonomy/term/44') {
    $sim_id = variable_get('ringo_eshop_sim_id', 30);
    drupal_goto('node/'. $sim_id);
  }
  drupal_add_js(drupal_get_path('module', 'ringo_eshop') . '/js/jquery-ui.js', array('group' => JS_THEME));
  drupal_add_css(drupal_get_path('module', 'ringo_eshop') . '/css/jquery-ui.css');
}

