<?php

/**
 * Implementation of hook_uc_checkout_pane()
 */

function ringo_eshop_uc_checkout_pane() {
  $panes[] = array(
    'id' => 'id_document',
    'title' => t('ID Document'),
     'desc' => t('Provide customers to add ID document information'),
     'callback' => 'ringo_eshop_id_document_pane_checkout',
     'process' => TRUE,
     'weight' => 3,
   );
  $panes[] = array(
    'id' => 'ringo_contact_info',
    'title' => t('Contact info'),
     'desc' => t('Provide customers to add contact information'),
     'callback' => 'ringo_eshop_contact_info_pane_checkout',
     'process' => TRUE,
     'weight' => 2,
   );

   return $panes;
}

/**
 * ID Document checkout pane function
 */
function ringo_eshop_id_document_pane_checkout($op, &$order, $form = NULL, &$form_state = NULL) {

  switch($op) {
    //CHECKOUT FORM
    case 'view':
      $contents['id_type'] = array(
        '#title' => 'Type',
        '#type' => 'select',
        '#options' => array(
          '1' => t('ID'),
          '2' => t('Passport'),
        ),
        '#required' =>  TRUE,
        //'#default_value' => $arg1->shipping_insurance['accept'] ? $arg1->shipping_insurance['accept'] : NULL,
      );
      $contents['id_number'] = array(
        '#type' => 'textfield',
        '#title' => t('Number'),
        '#required' => TRUE,
      );
      $contents['id_expiry_date'] = array(
        '#title' => t('Expiry date'),
        '#type' => 'date_popup',
        '#date_format' => 'm/d/Y',
        '#date_label_position' => 'within',
        '#date_increment' => 15,
        '#date_year_range' => '0:+8',
      );
      $contents['id_card'] = array(
        '#type' => 'file',
        '#title' => t('Image'),
        '#description' => t('Upload ID card & Tax code'),
      );
      return array('description' => '', 'contents' => $contents);

    //CHECKOUT PROCESSING - load values into order object.
    case 'process':
      if (empty($form_state['values']['panes']['id_document']['id_type'])) {
        form_set_error('panes][id_document][id_type', t('You cannot check out without selecting an ID type.'));
        return FALSE;
      }
      if (empty($form_state['values']['panes']['id_document']['id_number'])) {
        form_set_error('panes][id_document][id_number', t('You cannot check out without adding ID number.'));
        return FALSE;
      }
      $order->data['id_type'] = $form_state['values']['panes']['id_document']['id_type'];
      $order->data['id_number'] = $form_state['values']['panes']['id_document']['id_number'];
      $order->data['id_expiry_date'] = $form_state['values']['panes']['id_document']['id_expiry_date'];

      return TRUE;

    //CHECKOUT REVIEW
    case 'review':
      $message[] = array(
        'title' => t('ID Type'),
        'data' => $order->data['id_type'],
      );
      $message[] = array(
        'title' => t('ID Number'),
        'data' => $order->data['id_number'],
      );
      $message[] = array(
        'title' => t('Expiry date'),
        'data' => $order->data['id_expiry_date'],
      );
      return $message;
  }
}

/**
 * ID Document checkout pane function
 */
function ringo_eshop_contact_info_pane_checkout($op, &$order, $form = NULL, &$form_state = NULL) {

  switch($op) {
    //CHECKOUT FORM
    case 'view':
      $contents['contact_title'] = array(
        '#title' => t('Title'),
        '#type' => 'select',
        '#options' => array(
          '1' => t('Mr'),
          '2' => t('Ms'),
        ),
        '#required' =>  TRUE,
      );
      $contents['contact_gender'] = array(
        '#title' => t('Gender'),
        '#type' => 'select',
        '#options' => array(
          '1' => t('Male'),
          '2' => t('Female'),
        ),
        '#required' =>  TRUE,
      );
      $contents['contact_birth_date'] = array(
        '#title' => t('Date of birth'),
        '#type' => 'date_popup',
        '#date_format' => 'm/d/Y',
        '#date_label_position' => 'within',
        '#date_increment' => 15,
        '#date_year_range' => '0:+8',
      );
      return array('description' => '', 'contents' => $contents);

    //CHECKOUT PROCESSING - load values into order object.
    case 'process':
      $order->data['contact_title'] = $form_state['values']['panes']['ringo_contact_info']['contact_title'];
      $order->data['contact_gender'] = $form_state['values']['panes']['ringo_contact_info']['contact_gender'];
      $order->data['contact_birth_date'] = $form_state['values']['panes']['ringo_contact_info']['contact_birth_date'];

      return TRUE;

    //CHECKOUT REVIEW
    case 'review':
      $message[] = array(
        'title' => t('Title'),
        'data' => $order->data['contact_title'],
      );
      $message[] = array(
        'title' => t('Gender'),
        'data' => $order->data['contact_gender'],
      );
      $message[] = array(
        'title' => t('Date of birth'),
        'data' => $order->data['contact_birth_date'],
      );
      return $message;
  }
}

function ringo_eshop_uc_add_to_cart($nid, $qty, $data) {
  $sim_id = variable_get('ringo_eshop_sim_id', 30);
  if ($nid == $sim_id) {
    global $user;
    $oid = $data['attributes'][2];
    db_insert('ringo_eshop_numbers')
      ->fields(array(
        'oid' => $oid,
        'uid' => $user->uid,
        'status' => 1,
      ))
      ->execute();
  }
}

function ringo_eshop_form_alter(&$form, &$form_state, $form_id) {
  $sim_id = variable_get('ringo_eshop_sim_id', 30);
  if ($form_id == 'uc_product_add_to_cart_form_'.$sim_id) {
    $query = db_select('ringo_eshop_numbers', 'rn');
    $query->addField('rn', 'oid');
    $locked_options = $query->execute()->fetchAllKeyed(0, 0);
    $form['attributes'][2]['#options'] = array_diff_key($form['attributes'][2]['#options'], $locked_options);
    // add national offers
    $summary_text = t('You designed an offer of !blue_start !voice minutes, !sms SMS &amp; !data GB !blue_end for
  an estimated monthly bill of !price € / month',
      array(
        '!blue_start' => '<span class="blue-color">',
        '!voice' => '<span class="voice">0</span>',
        '!sms' => '<span class="sms">0</span>',
        '!data' => '<span class="data">0</span>',
        '!price' => '<span class="purple-color"> <span class="total">0</span>',
        '!blue_end' => '</span>',
      ));
    //$form['attributes'][4]['#description'] = format_string('<p class="nat-bundle-desc">!summary</p>', array('!summary' => $summary_text));
    $form['attributes'][4]['#prefix'] = '<div id="national-bundle-details">';
    $form['attributes'][4]['#suffix'] = format_string('<p class="nat-bundle-desc">!summary</p>', array('!summary' => $summary_text)) .'</div>';
    $form += _ringo_eshop_build_national_offers();
  }
}

function ringo_eshop_uc_cart_item_delete($entity) {
  $sim_id = variable_get('ringo_eshop_sim_id', 30);
  if ($entity->nid == $sim_id) {
    $oid =  $entity->data['attributes'][2];
    db_delete('ringo_eshop_numbers')
      ->condition('oid', $oid)
      ->execute();
  }
}

function _ringo_eshop_build_national_offers() {
  $national_offers = array();
  $cid = 'national_offers';
  if ($cache = cache_get($cid)) {
    $national_offers = $cache->data;
  }
  return assign_national_bundle_form($national_offers);
}

function assign_national_bundle_form($national_bundles) {
  $headers = array('');
  $rows = array();
  foreach ($national_bundles as $type => $packages) {
    $row = array(
      'data' => array(),
      'class' => array(strtolower($type)),
      'group' => array(strtolower($type)),
    );

    $options = array();
    $row['data'][] = array('data' => t($type), 'class' => array('package'));

    foreach ($packages as $size => $package) {
      $cell = array(
        'data' => format_string('<span class="size">!quantity</span>', array('!quantity' => $package['quantity'])) . '<br />'
          . format_string('!currency <span class="price">!price</span>', array('!currency' => t('€'), '!price' => $package['price'])),
        'package-id' => $package['id'],
      );

      $options[$package['id']] = $package['service_name'];

      $row['data'][] = $cell;

      if (!in_array($size, $headers)) {
        $headers[] = $size;
      }
    }

    $rows[] = $row;
    $form[strtolower($type)] = array(
      '#type' => 'radios',
      '#title' => $type,
      '#options' => $options,
    );
  }

  $form['nat-table'] = array(
    '#prefix' => '<div id ="nat-bundle-options">',
    '#markup' => theme(
        'table', array(
          'header' => $headers,
          'rows' => $rows,
          'attributes' => array('class' => array('nat-bundle')),
        )
      ),
    '#suffix' => '</div>',
  );

  drupal_add_js(drupal_get_path('module', 'ringo_eshop') . '/js/national_bundles.js', array('group' => JS_THEME));

  return $form;
}

